# kubernetes/security/rbac/role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: picura-admin-binding
subjects:
- kind: Group
  name: picura-aks-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: picura-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: picura-developer-binding
  namespace: development
subjects:
- kind: Group
  name: picura-aks-developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: picura-developer
  apiGroup: rbac.authorization.k8s.io