# kubernetes/networking/ingress-nginx.yaml

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.0.6
  values:
    controller:
      replicaCount: 2
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      extraArgs:
        default-ssl-certificate: "cert-manager/wildcard-tls"
    admissionWebhooks:
      enabled: true
      failurePolicy: Fail
      patch:
        enabled: true
    podSecurityPolicy:
      enabled: true